// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApMZLu1oA_Rib3EkymtEYloVpWKGC6cdU',
    appId: '1:277422856675:web:ea5438cc3244c9408168d6',
    messagingSenderId: '277422856675',
    projectId: 'esp32-test-9f190',
    authDomain: 'esp32-test-9f190.firebaseapp.com',
    databaseURL: 'https://esp32-test-9f190-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-test-9f190.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUmii0dPHTeFAFYNYwsap5CdaZ6zhyZ04',
    appId: '1:277422856675:android:d4f4282e01bc96a28168d6',
    messagingSenderId: '277422856675',
    projectId: 'esp32-test-9f190',
    databaseURL: 'https://esp32-test-9f190-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-test-9f190.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp0yVmJhXqYpd9i7UDiBnWf1PAIdbf4g8',
    appId: '1:277422856675:ios:4ceebb6388c5d18e8168d6',
    messagingSenderId: '277422856675',
    projectId: 'esp32-test-9f190',
    databaseURL: 'https://esp32-test-9f190-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-test-9f190.appspot.com',
    iosClientId: '277422856675-a7egah2al7mu031h1qis1247t3pv469v.apps.googleusercontent.com',
    iosBundleId: 'com.example.personDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp0yVmJhXqYpd9i7UDiBnWf1PAIdbf4g8',
    appId: '1:277422856675:ios:4ceebb6388c5d18e8168d6',
    messagingSenderId: '277422856675',
    projectId: 'esp32-test-9f190',
    databaseURL: 'https://esp32-test-9f190-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-test-9f190.appspot.com',
    iosClientId: '277422856675-a7egah2al7mu031h1qis1247t3pv469v.apps.googleusercontent.com',
    iosBundleId: 'com.example.personDetector',
  );
}
